FROM python:3.9.1


RUN apt-get update && apt-get install -y wget
RUN pip install pandas psycopg2 pyarrow
RUN pip install sqlalchemy  
WORKDIR /app
COPY ingest_green_tripdata.py ingest_green_tripdata.py

ENTRYPOINT [ "python", "ingest_green_tripdata.py" ]